name: Quality

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  BASIC_AUTH_USERNAME: test
  BASIC_AUTH_PASSWORD_HASH: "$argon2id$v=19$m=4096,t=3,p=1$5jaCLPecde+XF3q5n3sAT/ZqZiDx$FQ8THOm28zf4Q+SpWkwJRB7FrPjixgvACd5uErllMVY"

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno fmt --check .

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint .

  type-check:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install --frozen
      - run: deno check

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install --frozen
      - run: deno task test

  build:
    name: Production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install --frozen
      - run: deno task build
